version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: banking-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: banking-backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://root:example@mongodb:27017/bankingdb?authSource=admin
      NODE_ENV: development
      FRONTEND_URI: http://localhost:3000
      JWT_SECRET: dev-secret-change-in-prod
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: banking-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_BASE_URI: http://localhost:8000/api/v1
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongo_data:
